import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import ReduxProvider from "./redux-provider";

export const metadata: Metadata = {
  title: "MxLogBook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <ReduxProvider>
            {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
